name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy-to-flyio:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - run: pip install hatch

      - name: Build with Hatch and write requirements file
        run: |
          hatch build
          hatch dep show requirements >requirements.txt

      - run: |
          flyctl deploy --verbose --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  purge-profile-readme:
    needs: [ deploy-to-flyio ]
    uses: ./.github/workflows/purge_profile_readme.yml
