name: Deploy to Fly.io

on:
  push:
    branches:
      - master

env:
  REPO_OWNER: tuokri

jobs:
  deploy-to-flyio:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Check running on repo owner
        uses: actions/github-script@v7
        if: ${{ github.repository_owner != env.REPO_OWNER }}
        with:
          script: core.setFailed('action is not running on repository owner!')

      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - run: pip install hatch

      - name: Build with Hatch and write requirements file
        run: |
          hatch build
          hatch dep show requirements > requirements.txt

      - run: |
          flyctl deploy --verbose --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  purge-profile-readme:
    needs: [ deploy-to-flyio ]
    uses: ./.github/workflows/purge_profile_readme.yml

  get-readme-page-to-warm-up-cache:
    needs: [ purge-profile-readme ]
    runs-on: ubuntu-latest
    steps:
      - name: Check running on repo owner
        uses: actions/github-script@v7
        if: ${{ github.repository_owner != env.REPO_OWNER }}
        with:
          script: core.setFailed('action is not running on repository owner!')

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - run: pip install hatch

      - name: Build with Hatch and write requirements file
        run: |
          hatch build

      - run: python ./warm_up_caches.py
