name: Purge profile README

on: [ workflow_call ]

jobs:
  purge-profile-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Purge all cached camo images
        run: |
          urls=$(curl -sLk https://github.com/tuokri/tuokri/tree/master | grep -Eo "(http|https)://camo.githubusercontent.com[a-zA-Z0-9./?=_%:-]*")

          while IFS= read -r line; do curl -X PURGE $line ; done <<< $urls
